import type { Container, Vehicle } from "./types";

export const containers: Container[] = [
  {
    id: "CT-001",
    containerNumber: "MSCU7845621",
    type: "40ft HC",
    origin: "Shanghai, CN",
    destination: "Rotterdam, NL",
    status: "in-transit",
    eta: "2026-05-28",
    weight: 24.5,
    carrier: "Maersk Line",
    lastUpdate: "2 min ago",
    progress: 68,
  },
  {
    id: "CT-002",
    containerNumber: "TCLU3298710",
    type: "20ft Standard",
    origin: "Singapore, SG",
    destination: "Los Angeles, US",
    status: "at-port",
    eta: "2026-05-25",
    weight: 18.2,
    carrier: "COSCO Shipping",
    lastUpdate: "15 min ago",
    progress: 45,
  },
  {
    id: "CT-003",
    containerNumber: "HLBU5562349",
    type: "40ft Reefer",
    origin: "Hamburg, DE",
    destination: "Dubai, AE",
    status: "customs",
    eta: "2026-05-24",
    weight: 22.8,
    carrier: "Hapag-Lloyd",
    lastUpdate: "1 hr ago",
    progress: 82,
  },
  {
    id: "CT-004",
    containerNumber: "CMAU9012345",
    type: "45ft HC",
    origin: "Busan, KR",
    destination: "Felixstowe, UK",
    status: "delayed",
    eta: "2026-06-02",
    weight: 26.1,
    carrier: "CMA CGM",
    lastUpdate: "30 min ago",
    progress: 55,
  },
  {
    id: "CT-005",
    containerNumber: "OOLU7789012",
    type: "20ft Standard",
    origin: "Mumbai, IN",
    destination: "Antwerp, BE",
    status: "delivered",
    eta: "2026-05-20",
    weight: 16.4,
    carrier: "OOCL",
    lastUpdate: "3 hrs ago",
    progress: 100,
  },
  {
    id: "CT-006",
    containerNumber: "FCIU4456789",
    type: "40ft Flat Rack",
    origin: "Houston, US",
    destination: "Santos, BR",
    status: "in-transit",
    eta: "2026-05-30",
    weight: 31.7,
    carrier: "MSC",
    lastUpdate: "5 min ago",
    progress: 38,
  },
];

export const vehicles: Vehicle[] = [
  {
    id: "FL-101",
    name: "Truck Alpha-7",
    type: "Heavy Haul Tractor",
    driver: "James Mitchell",
    location: "I-10, Phoenix AZ",
    coordinates: { lat: 33.4484, lng: -112.074 },
    status: "active",
    speed: 72,
    fuel: 68,
    cargo: "Industrial Turbine (142T)",
    lastPing: "30 sec ago",
  },
  {
    id: "FL-102",
    name: "Truck Beta-3",
    type: "Modular Trailer",
    driver: "Sarah Chen",
    location: "Port of Houston, TX",
    coordinates: { lat: 29.7604, lng: -95.3698 },
    status: "idle",
    speed: 0,
    fuel: 91,
    cargo: "Awaiting Load",
    lastPing: "2 min ago",
  },
  {
    id: "FL-103",
    name: "Truck Gamma-12",
    type: "Lowboy Trailer",
    driver: "Marcus Johnson",
    location: "US-287, Amarillo TX",
    coordinates: { lat: 35.222, lng: -101.8313 },
    status: "active",
    speed: 58,
    fuel: 45,
    cargo: "Wind Turbine Blade Set",
    lastPing: "45 sec ago",
  },
  {
    id: "FL-104",
    name: "Truck Delta-5",
    type: "Multi-Axle SPMT",
    driver: "Elena Rodriguez",
    location: "Maintenance Yard, Dallas TX",
    coordinates: { lat: 32.7767, lng: -96.797 },
    status: "maintenance",
    speed: 0,
    fuel: 22,
    cargo: "None",
    lastPing: "1 hr ago",
  },
  {
    id: "FL-105",
    name: "Truck Echo-9",
    type: "Heavy Haul Tractor",
    driver: "David Park",
    location: "I-35, Oklahoma City OK",
    coordinates: { lat: 35.4676, lng: -97.5164 },
    status: "active",
    speed: 65,
    fuel: 74,
    cargo: "Transformer Unit (98T)",
    lastPing: "1 min ago",
  },
  {
    id: "FL-106",
    name: "Truck Foxtrot-2",
    type: "Flatbed Trailer",
    driver: "Unassigned",
    location: "Depot, Memphis TN",
    coordinates: { lat: 35.1495, lng: -90.049 },
    status: "offline",
    speed: 0,
    fuel: 55,
    cargo: "None",
    lastPing: "6 hrs ago",
  },
];

export const cargoTypes = [
  "General Cargo",
  "Heavy Machinery",
  "Hazardous Materials",
  "Refrigerated Goods",
  "Oversized Load",
  "Containerized Freight",
];

export const containerStatusLabels: Record<
  Container["status"],
  { label: string; color: string }
> = {
  "in-transit": { label: "In Transit", color: "bg-blue-100 text-blue-800" },
  "at-port": { label: "At Port", color: "bg-purple-100 text-purple-800" },
  customs: { label: "Customs", color: "bg-amber-100 text-amber-800" },
  delivered: { label: "Delivered", color: "bg-green-100 text-green-800" },
  delayed: { label: "Delayed", color: "bg-red-100 text-red-800" },
};

export const fleetStatusLabels: Record<
  Vehicle["status"],
  { label: string; color: string }
> = {
  active: { label: "Active", color: "bg-green-100 text-green-800" },
  idle: { label: "Idle", color: "bg-amber-100 text-amber-800" },
  maintenance: { label: "Maintenance", color: "bg-orange-100 text-orange-800" },
  offline: { label: "Offline", color: "bg-gray-100 text-gray-600" },
};
